version: '3'
services:
  phore:
    build: .
    network_mode: "host"
    volumes:
      - 'phore-data:/phore'
    container_name: phore-node
    restart: always
    logging:
      options:
        max-size: 1g
    image: 'tjennerjahn/cryptocoindaemon:phore'
volumes:
  phore-data:
    external: false
