version: '3'
services:
  rapids:
    build: .
    network_mode: "host"
    volumes:
      - 'rapids-data:/rapids'
    container_name: rapids-node
    restart: always
    logging:
      options:
        max-size: 1g
    image: 'tjennerjahn/cryptocoindaemon:rapids'
volumes:
  rapids-data:
    external: false
