version: '3'
services:
  merebel:
    network_mode: "host"
    volumes:
      - 'merebel-data:/merebel'
    container_name: merebel-node
    restart: always
    logging:
      options:
        max-size: 1g
    image: 'tjennerjahn/cryptocoindaemon:merebel'
  merebel_sync:
    network_mode: "host"
    container_name: merebel-sync
    image: 'tjennerjahn/cryptocoindaemon:dbsync'
    environment:
      TASK_SCHEDULE: '*/10 * * * *'
      NPM_COMMAND: 'start'
      COIN_NAME: 'merebel'
volumes:
  merebel-data:
    external: false
