version: '3'
services:
  zcash:
    network_mode: "host"
    volumes:
      - 'zcash-data:/zcash'
    container_name: zcash-node
    restart: always
    logging:
      options:
        max-size: 1g
    image: 'tjennerjahn/cryptocoindaemon:zcash'
  zcash_sync:
    network_mode: "host"
    container_name: zcash-sync
    image: 'tjennerjahn/cryptocoindaemon:dbsync'
    environment:
      TASK_SCHEDULE: '*/10 * * * *'
      NPM_COMMAND: 'start'
      COIN_NAME: 'zcash'
volumes:
  zcash-data:
    external: false
