version: '3'
services:
  divi:
    build: .
    network_mode: "host"
    volumes:
      - 'divi-data:/divi'
    container_name: divi-node
    restart: always
    logging:
      options:
        max-size: 1g
    image: 'tjennerjahn/cryptocoindaemon:divi'
volumes:
  divi-data:
    external: false
