version: '3'
services:
  energi:
    network_mode: "host"
    volumes:
      - 'energi-data:/energi'
    container_name: energi-node
    restart: always
    logging:
      options:
        max-size: 1g
    image: 'tjennerjahn/cryptocoindaemon:energi'
  energi_sync:
    network_mode: "host"
    container_name: energi-sync
    image: 'tjennerjahn/cryptocoindaemon:dbsync'
    environment:
      TASK_SCHEDULE: '*/10 * * * *'
      NPM_COMMAND: 'start'
      COIN_NAME: 'energi'
volumes:
  energi-data:
    external: false
