version: '3'
services:
  zcoin:
    build: .
    network_mode: "host"
    volumes:
      - 'zcoin-data:/zcoin'
    container_name: zcoin-node
    restart: always
    logging:
      options:
        max-size: 1g
    image: 'tjennerjahn/cryptocoindaemon:zcoin'
volumes:
  zcoin-data:
    external: false
